apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-keyvault
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Release.Name }}-secrets
      type: Opaque
      data:
        - objectName: {{ .Values.keyVault.secretName }}
          key: DB_PASSWORD
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.serviceAccount.clientId | quote }}
    keyvaultName: {{ .Values.keyVault.vaultName | quote }}
    objects: |
      array:
        - |
          objectName: {{ .Values.keyVault.secretName }}
          objectType: secret
    tenantId: {{ .Values.serviceAccount.tenantId | default "" | quote }}